elasticsearch:
  image: elasticsearch:1.7
  volumes:
    - ./esdata:/usr/share/elasticsearch/data
    - ./esbackup:/backup
  ports:
    - "9200:9200"
kibana:
  image: kibana:4.1
  links:
    - elasticsearch
  ports:
    - "5601:5601"
